// GENERATED from github/linguist lib/linguist/languages.yml (MIT, © GitHub).
// extension/filename -> language name + linguist type. Collisions resolve to
// the shortest name, with manual overrides for known wrong picks (ts/rs/md),
// and TSX/JSX fold into TypeScript/JavaScript.

export const EXT_LANGUAGE: Record<string, string> = {
  "bsl": "1C Enterprise",
  "os": "1C Enterprise",
  "2da": "2-Dimensional Array",
  "4dm": "4D",
  "abap": "ABAP",
  "asddls": "ABAP CDS",
  "abnf": "ABNF",
  "asc": "AsciiDoc",
  "ash": "AGS Script",
  "aidl": "AIDL",
  "al": "AL",
  "alg": "ALGOL",
  "ampl": "AMPL",
  "mod": "XML",
  "g4": "ANTLR",
  "apib": "API Blueprint",
  "apl": "APL",
  "dyalog": "APL",
  "asl": "ASL",
  "dsl": "ASL",
  "asn": "ASN.1",
  "asn1": "ASN.1",
  "asax": "ASP.NET",
  "ascx": "ASP.NET",
  "ashx": "ASP.NET",
  "asmx": "ASP.NET",
  "aspx": "ASP.NET",
  "axd": "ASP.NET",
  "dats": "ATS",
  "hats": "ATS",
  "sats": "ATS",
  "as": "AngelScript",
  "adb": "Ada",
  "ada": "Ada",
  "ads": "Ada",
  "txt": "Text",
  "afm": "Adobe Font Metrics",
  "agda": "Agda",
  "ak": "Aiken",
  "aleo": "Aleo",
  "als": "Alloy",
  "apkbuild": "Alpine Abuild",
  "outjob": "Altium Designer",
  "pcbdoc": "Altium Designer",
  "prjpcb": "Altium Designer",
  "schdoc": "Altium Designer",
  "angelscript": "AngelScript",
  "lp": "Lambdapi",
  "ant.xml": "Ant Build System",
  "build.xml": "Ant Build System",
  "antlers.html": "Antlers",
  "antlers.php": "Antlers",
  "antlers.xml": "Antlers",
  "apacheconf": "ApacheConf",
  "vhost": "Nginx",
  "htaccess": "ApacheConf",
  "apache2.conf": "ApacheConf",
  "httpd.conf": "ApacheConf",
  "cls": "TeX",
  "apex": "Apex",
  "trigger": "Apex",
  "agc": "Apollo Guidance Computer",
  "applescript": "AppleScript",
  "scpt": "AppleScript",
  "arc": "Arc",
  "asciidoc": "AsciiDoc",
  "adoc": "AsciiDoc",
  "aj": "AspectJ",
  "asm": "Assembly",
  "a51": "Assembly",
  "i": "SWIG",
  "inc": "C++",
  "nas": "Nasal",
  "nasm": "Assembly",
  "s": "Assembly",
  "astro": "Astro",
  "asy": "Asymptote",
  "aug": "Augeas",
  "ahk": "AutoHotkey",
  "ah1": "AutoHotkey",
  "ah2": "AutoHotkey",
  "ahkl": "AutoHotkey",
  "au3": "AutoIt",
  "avdl": "Avro IDL",
  "awk": "Awk",
  "auk": "Awk",
  "gawk": "Awk",
  "mawk": "Awk",
  "nawk": "Awk",
  "b": "B",
  "mch": "B (Formal Method)",
  "bas": "B4X",
  "baml": "BAML",
  "bbcode": "BBCode",
  "bird.conf": "BIRD2",
  "bqn": "BQN",
  "bal": "Ballerina",
  "bat": "Batchfile",
  "cmd": "Batchfile",
  "gradlew.bat": "Batchfile",
  "mvnw.cmd": "Batchfile",
  "bf": "Beef",
  "befunge": "Befunge",
  "be": "Berry",
  "bib": "BibTeX",
  "bibtex": "BibTeX",
  "bst": "BuildStream",
  "bicep": "Bicep",
  "bicepparam": "Bicep",
  "bs": "Bikeshed",
  "bison": "Bison",
  "bb": "BitBake",
  "bbappend": "BitBake",
  "bbclass": "BitBake",
  "blade": "Blade",
  "blade.php": "Blade",
  "decls": "BlitzBasic",
  "bmx": "BlitzMax",
  "blp": "Blueprint",
  "bsv": "Bluespec",
  "boo": "Boo",
  "bpl": "Boogie",
  "brs": "Brightscript",
  "browserslistrc": "Browserslist",
  "browserslist": "Browserslist",
  "bru": "Bru",
  "c": "C",
  "cats": "C",
  "h": "C",
  "h.in": "C",
  "idc": "C",
  "cs": "C#",
  "cake": "C#",
  "cs.pp": "C#",
  "csx": "C#",
  "linq": "C#",
  "cpp": "C++",
  "c++": "C++",
  "cc": "C++",
  "cp": "C++",
  "cppm": "C++",
  "cxx": "C++",
  "h++": "C++",
  "hh": "C++",
  "hpp": "C++",
  "hxx": "C++",
  "inl": "C++",
  "ino": "C++",
  "ipp": "C++",
  "ixx": "C++",
  "re": "C++",
  "tcc": "C++",
  "tpp": "C++",
  "txx": "C++",
  "c-objdump": "C-ObjDump",
  "chs": "C2hs Haskell",
  "c3": "C3",
  "cds": "CAP CDS",
  "cil": "CIL",
  "clp": "CLIPS",
  "cmake": "CMake",
  "cmake.in": "CMake",
  "cmakelists.txt": "CMake",
  "cob": "COBOL",
  "cbl": "COBOL",
  "ccp": "COBOL",
  "cobol": "COBOL",
  "cpy": "COBOL",
  "codeowners": "CODEOWNERS",
  "dae": "COLLADA",
  "cql": "CQL",
  "cson": "CSON",
  "css": "CSS",
  "csv": "CSV",
  "cue": "CUE",
  "w": "CWeb",
  "cabal": "Cabal Config",
  "cabal.config": "Cabal Config",
  "cabal.project": "Cabal Config",
  "caddyfile": "Caddyfile",
  "cdc": "Cadence",
  "cairo": "Cairo",
  "mligo": "CameLIGO",
  "cj": "Cangjie",
  "capnp": "Cap'n Proto",
  "carbon": "Carbon",
  "mss": "CartoCSS",
  "ceylon": "Ceylon",
  "chpl": "Chapel",
  "ch": "xBase",
  "crc32": "Checksums",
  "md2": "Checksums",
  "md4": "Checksums",
  "md5": "Checksums",
  "sha1": "Checksums",
  "sha2": "Checksums",
  "sha224": "Checksums",
  "sha256": "Checksums",
  "sha256sum": "Checksums",
  "sha3": "Checksums",
  "sha384": "Checksums",
  "sha512": "Checksums",
  "md5sums": "Checksums",
  "sha1sums": "Checksums",
  "sha256sums": "Checksums",
  "sha256sums.txt": "Checksums",
  "sha512sums": "Checksums",
  "checksums.txt": "Checksums",
  "cksums": "Checksums",
  "md5sum.txt": "Checksums",
  "ck": "ChucK",
  "circom": "Circom",
  "cirru": "Cirru",
  "clw": "Clarion",
  "clar": "Clarity",
  "asp": "Classic ASP",
  "icl": "Clean",
  "dcl": "Clean",
  "click": "Click",
  "clj": "Clojure",
  "boot": "Clojure",
  "cl2": "Clojure",
  "cljc": "Clojure",
  "cljs": "Clojure",
  "cljs.hl": "Clojure",
  "cljscm": "Clojure",
  "cljx": "Clojure",
  "hic": "Clojure",
  "riemann.config": "Clojure",
  "soy": "Closure Templates",
  "firestore.rules": "Cloud Firestore Security Rules",
  "clue": "Clue",
  "conllu": "CoNLL-U",
  "conll": "CoNLL-U",
  "ql": "CodeQL",
  "qll": "CodeQL",
  "coffee": "CoffeeScript",
  "_coffee": "CoffeeScript",
  "cjsx": "CoffeeScript",
  "coffee.erb": "CoffeeScript",
  "iced": "CoffeeScript",
  "cakefile": "CoffeeScript",
  "cfm": "ColdFusion",
  "cfml": "ColdFusion",
  "cfc": "ColdFusion CFC",
  "lisp": "NewLisp",
  "asd": "Common Lisp",
  "cl": "Cool",
  "l": "Lex",
  "lsp": "NewLisp",
  "ny": "Common Lisp",
  "podsl": "Common Lisp",
  "sexp": "Common Lisp",
  "cwl": "Common Workflow Language",
  "cps": "Component Pascal",
  "cook": "Cooklang",
  "cppobjdump": "Cpp-ObjDump",
  "c++-objdump": "Cpp-ObjDump",
  "c++objdump": "Cpp-ObjDump",
  "cpp-objdump": "Cpp-ObjDump",
  "cxx-objdump": "Cpp-ObjDump",
  "creole": "Creole",
  "cr": "Crystal",
  "orc": "Csound",
  "udo": "Csound",
  "csd": "Csound Document",
  "sco": "Csound Score",
  "cu": "Cuda",
  "cuh": "Cuda",
  "curry": "Curry",
  "cy": "Cycript",
  "cylc": "Cylc",
  "suite.rc": "Cylc",
  "cyp": "Cypher",
  "cypher": "Cypher",
  "pyx": "Cython",
  "pxd": "Cython",
  "pxi": "Cython",
  "d": "D",
  "di": "D",
  "d-objdump": "D-ObjDump",
  "d2": "D2",
  "com": "DIGITAL Command Language",
  "dm": "DM",
  "zone": "DNS Zone",
  "arpa": "DNS Zone",
  "dfy": "Dafny",
  "darcspatch": "Darcs Patch",
  "dpatch": "Darcs Patch",
  "dart": "Dart",
  "das": "Daslang",
  "dwl": "DataWeave",
  "dsc": "DenizenScript",
  "dhall": "Dhall",
  "diff": "Diff",
  "patch": "Diff",
  "x": "RPC",
  "dockerfile": "Dockerfile",
  "containerfile": "Dockerfile",
  "djs": "Dogescript",
  "env": "Dotenv",
  "env.ci": "Dotenv",
  "env.dev": "Dotenv",
  "env.development": "Dotenv",
  "env.development.local": "Dotenv",
  "env.example": "Dotenv",
  "env.local": "Dotenv",
  "env.prod": "Dotenv",
  "env.production": "Dotenv",
  "env.sample": "Dotenv",
  "env.staging": "Dotenv",
  "env.template": "Dotenv",
  "env.test": "Dotenv",
  "env.testing": "Dotenv",
  "dune-project": "Dune",
  "dylan": "Dylan",
  "dyl": "Dylan",
  "intr": "Dylan",
  "lid": "Dylan",
  "e": "E",
  "eml": "E-mail",
  "mbox": "E-mail",
  "ebnf": "EBNF",
  "ecl": "ECL",
  "eclxml": "ECL",
  "ejs": "EJS",
  "ect": "EJS",
  "ejs.t": "EJS",
  "jst": "EJS",
  "eq": "EQ",
  "sch": "XML",
  "brd": "Eagle",
  "earthfile": "Earthly",
  "eb": "Easybuild",
  "epj": "Ecere Projects",
  "html": "HTML",
  "edge": "Edge",
  "edgeql": "EdgeQL",
  "esdl": "EdgeQL",
  "editorconfig": "EditorConfig",
  "edc": "Edje Data Collection",
  "ex": "Elixir",
  "exs": "Elixir",
  "mix.lock": "Elixir",
  "elm": "Elm",
  "elv": "Elvish",
  "el": "Emacs Lisp",
  "emacs": "Emacs Lisp",
  "emacs.desktop": "Emacs Lisp",
  "abbrev_defs": "Emacs Lisp",
  "gnus": "Emacs Lisp",
  "spacemacs": "Emacs Lisp",
  "viper": "Emacs Lisp",
  "cask": "Emacs Lisp",
  "eask": "Emacs Lisp",
  "project.ede": "Emacs Lisp",
  "_emacs": "Emacs Lisp",
  "em": "EmberScript",
  "emberscript": "EmberScript",
  "erl": "Erlang",
  "app": "Erlang",
  "app.src": "Erlang",
  "es": "Erlang",
  "escript": "Erlang",
  "hrl": "Erlang",
  "xrl": "Erlang",
  "yrl": "Erlang",
  "emakefile": "Erlang",
  "rebar.config": "Erlang",
  "rebar.config.lock": "Erlang",
  "rebar.lock": "Erlang",
  "fs": "F#",
  "fsi": "F#",
  "fsx": "F#",
  "fst": "F*",
  "fsti": "F*",
  "flf": "FIGlet Font",
  "fir": "FIRRTL",
  "fx": "FLUX",
  "flux": "FLUX",
  "fpp": "FPP",
  "fppi": "FPP",
  "factor": "Factor",
  "factor-boot-rc": "Factor",
  "factor-rc": "Factor",
  "fy": "Fancy",
  "fancypack": "Fancy",
  "fakefile": "Fancy",
  "fan": "Fantom",
  "dsp": "Faust",
  "fnl": "Fennel",
  "f": "Forth",
  "fbs": "FlatBuffers",
  "flix": "Flix",
  "ftl": "Fluent",
  "for": "Forth",
  "eam.fs": "Formatted",
  "fth": "Forth",
  "4th": "Forth",
  "forth": "Forth",
  "fr": "Text",
  "frt": "Forth",
  "f77": "Fortran",
  "f90": "Fortran Free Form",
  "f03": "Fortran Free Form",
  "f08": "Fortran Free Form",
  "f95": "Fortran Free Form",
  "bi": "FreeBASIC",
  "ftlh": "FreeMarker",
  "fut": "Futhark",
  "g": "GAP",
  "cnc": "G-code",
  "gco": "G-code",
  "gcode": "G-code",
  "gaml": "GAML",
  "gms": "GAMS",
  "gap": "GAP",
  "gd": "GDScript",
  "gi": "GAP",
  "tst": "GAP",
  "md": "Markdown",
  "gdb": "GDB",
  "gdbinit": "GDB",
  "gdshader": "GDShader",
  "gdshaderinc": "GDShader",
  "ged": "GEDCOM",
  "glsl": "GLSL",
  "fp": "GLSL",
  "frag": "GLSL",
  "frg": "GLSL",
  "fsh": "GLSL",
  "fshader": "GLSL",
  "geo": "GLSL",
  "geom": "GLSL",
  "glslf": "GLSL",
  "glslv": "GLSL",
  "gs": "GLSL",
  "gshader": "GLSL",
  "rchit": "GLSL",
  "rmiss": "GLSL",
  "shader": "GLSL",
  "tesc": "GLSL",
  "tese": "GLSL",
  "vert": "GLSL",
  "vrx": "GLSL",
  "vs": "GLSL",
  "vsh": "GLSL",
  "vshader": "GLSL",
  "gn": "GN",
  "gni": "GN",
  "gsc": "GSC",
  "csc": "GSC",
  "gsh": "GSC",
  "gml": "XML",
  "gemfile.lock": "Gemfile.lock",
  "gmi": "Gemini",
  "4gl": "Genero 4gl",
  "per": "Genero per",
  "kid": "Genshi",
  "ebuild": "Gentoo Ebuild",
  "eclass": "Gentoo Eclass",
  "gbr": "Gerber Image",
  "cmp": "Gerber Image",
  "gbl": "Gerber Image",
  "gbo": "Gerber Image",
  "gbp": "Gerber Image",
  "gbs": "Gerber Image",
  "gko": "Gerber Image",
  "gpb": "Gerber Image",
  "gpt": "Gerber Image",
  "gtl": "Gerber Image",
  "gto": "Gerber Image",
  "gtp": "Gerber Image",
  "gts": "Glimmer TS",
  "ncl": "NCL",
  "sol": "Solidity",
  "po": "Gettext Catalog",
  "pot": "Gettext Catalog",
  "feature": "Gherkin",
  "story": "Gherkin",
  "gitattributes": "Git Attributes",
  "gitmessage": "Git Commit",
  "commit_editmsg": "Git Commit",
  "gitconfig": "Git Config",
  "gitmodules": "Git Config",
  "tgitconfig": "Git Config",
  "config.worktree": "Git Config",
  "git-blame-ignore-revs": "Git Revision List",
  "gleam": "Gleam",
  "gjs": "Glimmer JS",
  "glf": "Glyph",
  "bdf": "Glyph Bitmap Distribution Format",
  "gno": "Gno",
  "gp": "Gnuplot",
  "gnu": "Gnuplot",
  "gnuplot": "Gnuplot",
  "p": "Gnuplot",
  "plot": "Gnuplot",
  "plt": "Prolog",
  "go": "Go",
  "go.sum": "Go Checksums",
  "go.work.sum": "Go Checksums",
  "go.mod": "Go Module",
  "gohtml": "Go Template",
  "gotmpl": "Go Template",
  "html.tmpl": "Go Template",
  "tmpl": "Go Template",
  "tpl": "Smarty",
  "_helpers.tpl": "Go Template",
  "go.work": "Go Workspace",
  "gdnlib": "Godot Resource",
  "gdns": "Godot Resource",
  "tres": "Godot Resource",
  "tscn": "Godot Resource",
  "project.godot": "Godot Resource",
  "golo": "Golo",
  "gst": "XML",
  "gsx": "Gosu",
  "vark": "Gosu",
  "grace": "Grace",
  "gradle": "Gradle",
  "gradle.kts": "Gradle Kotlin DSL",
  "gf": "Grammatical Framework",
  "graphql": "GraphQL",
  "gql": "GraphQL",
  "graphqls": "GraphQL",
  "dot": "Graphviz (DOT)",
  "gv": "Graphviz (DOT)",
  "groovy": "Groovy",
  "grt": "Groovy",
  "gtpl": "Groovy",
  "gvy": "Groovy",
  "jenkinsfile": "Groovy",
  "gsp": "Groovy Server Pages",
  "gtkrc": "GtkRC",
  "gtkrc-2.0": "GtkRC",
  "cfg": "INI",
  "haproxy.cfg": "HAProxy",
  "hcl": "HCL",
  "nomad": "HCL",
  "tf": "HCL",
  "tfvars": "HCL",
  "tofu": "HCL",
  "workflow": "HCL",
  "hip": "HIP",
  "hlsl": "HLSL",
  "cginc": "HLSL",
  "fxh": "HLSL",
  "hlsli": "HLSL",
  "hocon": "HOCON",
  "scalafix.conf": "HOCON",
  "scalafmt.conf": "HOCON",
  "hta": "HTML",
  "htm": "HTML",
  "html.hl": "HTML",
  "xht": "HTML",
  "xhtml": "HTML",
  "ecr": "HTML+ECR",
  "html.eex": "HTML+EEX",
  "heex": "HTML+EEX",
  "leex": "HTML+EEX",
  "erb": "HTML+ERB",
  "erb.deface": "HTML+ERB",
  "rhtml": "HTML+ERB",
  "phtml": "HTML+PHP",
  "cshtml": "HTML+Razor",
  "razor": "HTML+Razor",
  "http": "HTTP",
  "hxml": "HXML",
  "hack": "Hack",
  "hhi": "Hack",
  "php": "PHP",
  "haml": "Haml",
  "haml.deface": "Haml",
  "handlebars": "Handlebars",
  "hbs": "Handlebars",
  "hb": "Harbour",
  "ha": "Hare",
  "hs": "Haskell",
  "hs-boot": "Haskell",
  "hsc": "Haskell",
  "hx": "Haxe",
  "hxsl": "Haxe",
  "q": "q",
  "hql": "HiveQL",
  "hc": "HolyC",
  "hosts": "INI",
  "hosts.txt": "Hosts File",
  "hurl": "Hurl",
  "hy": "Hy",
  "pro": "IDL",
  "dlm": "IDL",
  "ipf": "IGOR Pro",
  "il": "IL Assembly",
  "ini": "INI",
  "cnf": "INI",
  "container": "INI",
  "dof": "INI",
  "frm": "INI",
  "lektorproject": "INI",
  "mount": "INI",
  "network": "INI",
  "prefs": "INI",
  "properties": "INI",
  "service": "INI",
  "socket": "INI",
  "target": "INI",
  "timer": "INI",
  "url": "INI",
  "buckconfig": "INI",
  "coveragerc": "INI",
  "flake8": "INI",
  "gitreview": "INI",
  "pylintrc": "INI",
  "buildozer.spec": "INI",
  "vlcrc": "INI",
  "irclog": "IRC log",
  "weechatlog": "IRC log",
  "ispc": "ISPC",
  "idr": "Idris",
  "lidr": "Idris",
  "gitignore": "Ignore List",
  "agignore": "Ignore List",
  "atomignore": "Ignore List",
  "babelignore": "Ignore List",
  "bzrignore": "Ignore List",
  "ckignore": "Ignore List",
  "coffeelintignore": "Ignore List",
  "cvsignore": "Ignore List",
  "dockerignore": "Ignore List",
  "easignore": "Ignore List",
  "eleventyignore": "Ignore List",
  "eslint-ignore": "Ignore List",
  "eslintignore": "Ignore List",
  "ignore": "Ignore List",
  "markdownlintignore": "Ignore List",
  "nodemonignore": "Ignore List",
  "npmignore": "Ignore List",
  "prettierignore": "Ignore List",
  "rgignore": "Ignore List",
  "stylelintignore": "Ignore List",
  "vercelignore": "Ignore List",
  "vscodeignore": "Ignore List",
  "gitignore-global": "Ignore List",
  "gitignore_global": "Ignore List",
  "hexpat": "ImHex Pattern Language",
  "ijm": "ImageJ Macro",
  "imba": "Imba",
  "ni": "Inform 7",
  "i7x": "Inform 7",
  "ink": "Ink",
  "iss": "Inno Setup",
  "isl": "Inno Setup",
  "io": "Io",
  "ik": "Ioke",
  "thy": "Isabelle",
  "root": "Isabelle ROOT",
  "ijs": "J",
  "manifest.mf": "JAR Manifest",
  "j": "JASS",
  "jcl": "JCL",
  "flex": "JFlex",
  "jflex": "JFlex",
  "json": "JSON",
  "4dform": "JSON",
  "4dproject": "JSON",
  "avsc": "JSON",
  "geojson": "JSON",
  "gltf": "JSON",
  "har": "JSON",
  "ice": "JSON",
  "json-tmlanguage": "JSON",
  "json.example": "JSON",
  "jsonl": "JSON",
  "mcmeta": "JSON",
  "sarif": "JSON",
  "slnlaunch": "JSON",
  "tact": "JSON",
  "tfstate": "JSON",
  "tfstate.backup": "JSON",
  "topojson": "JSON",
  "webapp": "JSON",
  "webmanifest": "JSON",
  "yy": "JSON",
  "yyp": "JSON",
  "all-contributorsrc": "JSON",
  "arcconfig": "JSON",
  "auto-changelog": "JSON",
  "c8rc": "JSON",
  "htmlhintrc": "JSON",
  "imgbotconfig": "JSON",
  "nycrc": "JSON",
  "releaserc": "JSON",
  "secrets.baseline": "JSON",
  "tern-config": "JSON",
  "tern-project": "JSON",
  "watchmanconfig": "JSON",
  "module.bazel.lock": "JSON",
  "package.resolved": "JSON",
  "pipfile.lock": "JSON",
  "bun.lock": "JSON",
  "composer.lock": "JSON",
  "deno.lock": "JSON",
  "flake.lock": "JSON",
  "mcmod.info": "JSON",
  "jsonc": "JSON with Comments",
  "code-snippets": "JSON with Comments",
  "code-workspace": "JSON with Comments",
  "hujson": "JSON with Comments",
  "sublime-build": "JSON with Comments",
  "sublime-color-scheme": "JSON with Comments",
  "sublime-commands": "JSON with Comments",
  "sublime-completions": "JSON with Comments",
  "sublime-keymap": "JSON with Comments",
  "sublime-macro": "JSON with Comments",
  "sublime-menu": "JSON with Comments",
  "sublime-mousemap": "JSON with Comments",
  "sublime-project": "JSON with Comments",
  "sublime-settings": "JSON with Comments",
  "sublime-theme": "JSON with Comments",
  "sublime-workspace": "JSON with Comments",
  "sublime_metrics": "JSON with Comments",
  "sublime_session": "JSON with Comments",
  "tsconfig.json": "JSON with Comments",
  "babelrc": "JSON with Comments",
  "devcontainer.json": "JSON with Comments",
  "eslintrc": "YAML",
  "eslintrc.json": "JSON with Comments",
  "jscsrc": "JSON with Comments",
  "jshintrc": "JSON with Comments",
  "jslintrc": "JSON with Comments",
  "oxlintrc.json": "JSON with Comments",
  "swcrc": "JSON with Comments",
  "api-extractor.json": "JSON with Comments",
  "jsconfig.json": "JSON with Comments",
  "language-configuration.json": "JSON with Comments",
  "tslint.json": "JSON with Comments",
  "json5": "JSON5",
  "jsonld": "JSONLD",
  "jq": "jq",
  "jac": "Jac",
  "jai": "Jai",
  "janet": "Janet",
  "java": "Java",
  "jav": "Java",
  "jsh": "Java",
  "jsp": "Java Server Pages",
  "tag": "Java Server Pages",
  "jte": "Java Template Engine",
  "js": "JavaScript",
  "_js": "JavaScript",
  "bones": "JavaScript",
  "cjs": "JavaScript",
  "es6": "JavaScript",
  "jake": "JavaScript",
  "javascript": "JavaScript",
  "jsb": "JavaScript",
  "jscad": "JavaScript",
  "jsfl": "JavaScript",
  "jslib": "JavaScript",
  "jsm": "JavaScript",
  "jspre": "JavaScript",
  "jss": "JavaScript",
  "jsx": "JavaScript",
  "mjs": "JavaScript",
  "njs": "JavaScript",
  "pac": "JavaScript",
  "sjs": "JavaScript",
  "ssjs": "JavaScript",
  "xsjs": "JavaScript",
  "xsjslib": "JavaScript",
  "jakefile": "JavaScript",
  "js.erb": "JavaScript+ERB",
  "snap": "Jest Snapshot",
  "mps": "JetBrains MPS",
  "mpl": "JetBrains MPS",
  "msd": "JetBrains MPS",
  "jinja": "Jinja",
  "j2": "Jinja",
  "jinja2": "Jinja",
  "jison": "Jison",
  "jisonlex": "Jison Lex",
  "ol": "Jolie",
  "iol": "Jolie",
  "jsonnet": "Jsonnet",
  "libsonnet": "Jsonnet",
  "jl": "Julia",
  "ipynb": "Jupyter Notebook",
  "notebook": "Jupyter Notebook",
  "just": "Just",
  "justfile": "Just",
  "k": "KCL",
  "kcl.mod": "KCL",
  "kcl.mod.lock": "KCL",
  "kdl": "KDL",
  "krl": "KRL",
  "ksy": "Kaitai Struct",
  "kak": "KakouneScript",
  "kakrc": "KakouneScript",
  "ks": "Kickstart",
  "kicad_pcb": "KiCad Layout",
  "kicad_mod": "KiCad Layout",
  "kicad_wks": "KiCad Layout",
  "fp-lib-table": "KiCad Layout",
  "kicad_sch": "KiCad Schematic",
  "kicad_sym": "KiCad Schematic",
  "kit": "Kit",
  "kk": "Koka",
  "kt": "Kotlin",
  "ktm": "Kotlin",
  "kts": "Kotlin",
  "csl": "XML",
  "kql": "Kusto",
  "lfe": "LFE",
  "ll": "LLVM",
  "lol": "LOLCODE",
  "lsl": "LSL",
  "lslp": "LSL",
  "lvproj": "LabVIEW",
  "lvclass": "LabVIEW",
  "lvlib": "LabVIEW",
  "langium": "Langium",
  "lark": "Lark",
  "lasso": "Lasso",
  "las": "Lasso",
  "lasso8": "Lasso",
  "lasso9": "Lasso",
  "latte": "Latte",
  "lean": "Lean",
  "hlean": "Lean",
  "leo": "Leo",
  "less": "Less",
  "lex": "Lex",
  "lexer.x": "Lex",
  "ligo": "LigoLANG",
  "ly": "LilyPond",
  "ily": "LilyPond",
  "m": "M",
  "ld": "Linker Script",
  "lds": "Linker Script",
  "ld.script": "Linker Script",
  "liquid": "Liquid",
  "liq": "Liquidsoap",
  "lagda": "Literate Agda",
  "litcoffee": "Literate CoffeeScript",
  "coffee.md": "Literate CoffeeScript",
  "lhs": "Literate Haskell",
  "livecodescript": "LiveCode Script",
  "ls": "LiveScript",
  "_ls": "LiveScript",
  "slakefile": "LiveScript",
  "lobster": "Lobster",
  "xm": "Logos",
  "xi": "Logos",
  "lgt": "Logtalk",
  "logtalk": "Logtalk",
  "lkml": "LookML",
  "lookml": "LookML",
  "lua": "Lua",
  "fcgi": "Lua",
  "nse": "Lua",
  "p8": "Lua",
  "pd_lua": "Lua",
  "rbxs": "Lua",
  "rockspec": "Lua",
  "wlua": "Lua",
  "luacheckrc": "Lua",
  "luau": "Luau",
  "mumps": "M",
  "m3u": "M3U",
  "m3u8": "M3U",
  "m4": "M4",
  "mc": "M4",
  "configure.ac": "M4Sugar",
  "matlab": "MATLAB",
  "ms": "Roff",
  "mcr": "MAXScript",
  "mdx": "MDX",
  "mlir": "MLIR",
  "mq4": "MQL4",
  "mqh": "MQL4",
  "mq5": "MQL5",
  "mtml": "MTML",
  "muf": "MUF",
  "m2": "Macaulay2",
  "mak": "Makefile",
  "make": "Makefile",
  "makefile": "Makefile",
  "mk": "Makefile",
  "mkfile": "Makefile",
  "bsdmakefile": "Makefile",
  "gnumakefile": "Makefile",
  "kbuild": "Makefile",
  "makefile.am": "Makefile",
  "makefile.boot": "Makefile",
  "makefile.frag": "Makefile",
  "makefile.in": "Makefile",
  "makefile.inc": "Makefile",
  "makefile.pc": "Makefile",
  "makefile.wat": "Makefile",
  "makefile.sco": "Makefile",
  "mako": "Mako",
  "mao": "Mako",
  "livemd": "Markdown",
  "markdown": "Markdown",
  "mdown": "Markdown",
  "mdwn": "Markdown",
  "mkd": "Markdown",
  "mkdn": "Markdown",
  "mkdown": "Markdown",
  "ronn": "Markdown",
  "scd": "Markdown",
  "workbook": "Markdown",
  "contents.lr": "Markdown",
  "marko": "Marko",
  "mask": "Mask",
  "pom.xml": "Maven POM",
  "maxpat": "Max",
  "maxhelp": "Max",
  "maxproj": "Max",
  "mxt": "Max",
  "pat": "Max",
  "metta": "MeTTa",
  "moo": "Mercury",
  "mmd": "Mermaid",
  "mermaid": "Mermaid",
  "meson.build": "Meson",
  "meson_options.txt": "Meson",
  "metal": "Metal",
  "sln": "Microsoft Visual Studio Solution",
  "minid": "MiniD",
  "yaml": "YAML",
  "yml": "YAML",
  "mzn": "MiniZinc",
  "dzn": "MiniZinc Data",
  "mint": "Mint",
  "druby": "Mirah",
  "duby": "Mirah",
  "mirah": "Mirah",
  "mo": "Motoko",
  "i3": "Modula-3",
  "ig": "Modula-3",
  "m3": "Modula-3",
  "mg": "Modula-3",
  "mms": "Module Management System",
  "mmk": "Module Management System",
  "descrip.mmk": "Module Management System",
  "descrip.mms": "Module Management System",
  "mojo": "XML",
  "monkey": "Monkey",
  "monkey2": "Monkey",
  "mbt": "MoonBit",
  "moon": "MoonScript",
  "x68": "Motorola 68K Assembly",
  "move": "Move",
  "muse": "Muse",
  "mustache": "Mustache",
  "myt": "Myghty",
  "nasl": "NASL",
  "neon": "NEON",
  "nl": "NL",
  "npmrc": "NPM Config",
  "nsi": "NSIS",
  "nsh": "NSIS",
  "nss": "NWScript",
  "ne": "Nearley",
  "nearley": "Nearley",
  "n": "Roff",
  "axs": "NetLinx",
  "axi": "NetLinx",
  "axs.erb": "NetLinx+ERB",
  "axi.erb": "NetLinx+ERB",
  "nlogo": "NetLogo",
  "nf": "Nextflow",
  "nextflow.config": "Nextflow",
  "nginx": "Nginx",
  "nginxconf": "Nginx",
  "nginx.conf": "Nginx",
  "nim": "Nim",
  "nim.cfg": "Nim",
  "nimble": "Nim",
  "nimrod": "Nim",
  "nims": "Nim",
  "ninja": "Ninja",
  "nit": "Nit",
  "nix": "Nix",
  "nr": "Noir",
  "nu": "Nu",
  "nukefile": "Nu",
  "numpy": "NumPy",
  "numpyw": "NumPy",
  "numsc": "NumPy",
  "njk": "Nunjucks",
  "ml": "OCaml",
  "eliom": "OCaml",
  "eliomi": "OCaml",
  "ml4": "OCaml",
  "mli": "OCaml",
  "mll": "OCaml",
  "mly": "OCaml",
  "msg": "OMNeT++ MSG",
  "ned": "OMNeT++ NED",
  "ob2": "Oberon",
  "objdump": "ObjDump",
  "odin": "Odin",
  "mm": "XML",
  "sj": "Objective-J",
  "omgrofl": "Omgrofl",
  "opa": "Opa",
  "opal": "Opal",
  "rego": "Open Policy Agent",
  "opencl": "OpenCL",
  "qasm": "OpenQASM",
  "scad": "OpenSCAD",
  "plist": "XML Property List",
  "glyphs": "OpenStep Property List",
  "fea": "OpenType Feature File",
  "ackrc": "Option List",
  "rspec": "Option List",
  "yardopts": "Option List",
  "mocha.opts": "Option List",
  "org": "Org",
  "opy": "OverPy",
  "overpassql": "OverpassQL",
  "ox": "Ox",
  "oxh": "Ox",
  "oxo": "Ox",
  "oxygene": "Oxygene",
  "oz": "Oz",
  "p4": "P4",
  "pddl": "PDDL",
  "pegjs": "PEG.js",
  "peggy": "PEG.js",
  "aw": "PHP",
  "ctp": "PHP",
  "php3": "PHP",
  "php4": "PHP",
  "php5": "PHP",
  "phps": "PHP",
  "phpt": "PHP",
  "php_cs": "PHP",
  "php_cs.dist": "PHP",
  "phakefile": "PHP",
  "pls": "PLSQL",
  "bdy": "PLSQL",
  "ddl": "SQL",
  "fnc": "PLSQL",
  "pck": "PLSQL",
  "pkb": "PLSQL",
  "pks": "PLSQL",
  "plb": "PLSQL",
  "plsql": "PLSQL",
  "prc": "SQL",
  "spc": "PLSQL",
  "sql": "SQL",
  "tpb": "PLSQL",
  "tps": "PLSQL",
  "trg": "PLSQL",
  "vw": "PLSQL",
  "pgsql": "PLpgSQL",
  "pov": "POV-Ray SDL",
  "pact": "Pact",
  "pan": "Pan",
  "psc": "Papyrus",
  "parrot": "Parrot",
  "pasm": "Parrot Assembly",
  "pir": "Parrot Internal Representation",
  "pas": "Pascal",
  "dfm": "Pascal",
  "dpr": "Pascal",
  "lpr": "Pascal",
  "pascal": "Pascal",
  "pp": "Pascal",
  "pwn": "Pawn",
  "sma": "Pawn",
  "pep": "Pep8",
  "pl": "Perl",
  "cgi": "Perl",
  "perl": "Perl",
  "ph": "Perl",
  "plx": "Perl",
  "pm": "Perl",
  "psgi": "Perl",
  "t": "Perl",
  "latexmkrc": "Perl",
  "makefile.pl": "Perl",
  "rexfile": "Perl",
  "ack": "Perl",
  "cpanfile": "Perl",
  "pic": "Pic",
  "chem": "Pic",
  "pkl": "Pkl",
  "pig": "PigLatin",
  "pike": "Pike",
  "pmod": "Pike",
  "dev-requirements.txt": "Pip Requirements",
  "requirements-dev.txt": "Pip Requirements",
  "requirements.lock.txt": "Pip Requirements",
  "requirements.txt": "Pip Requirements",
  "puml": "PlantUML",
  "iuml": "PlantUML",
  "plantuml": "PlantUML",
  "pod": "Pod",
  "pod6": "Pod 6",
  "pogo": "PogoScript",
  "polar": "Polar",
  "pony": "Pony",
  "por": "Portugol",
  "pcss": "PostCSS",
  "postcss": "PostCSS",
  "ps": "PostScript",
  "eps": "PostScript",
  "epsi": "PostScript",
  "pfa": "PostScript",
  "pq": "Power Query",
  "pbt": "PowerBuilder",
  "sra": "PowerBuilder",
  "sru": "PowerBuilder",
  "srw": "PowerBuilder",
  "ps1": "PowerShell",
  "psd1": "PowerShell",
  "psm1": "PowerShell",
  "praat": "Praat",
  "prisma": "Prisma",
  "pc": "Pro*C",
  "pde": "Processing",
  "procfile": "Procfile",
  "prolog": "Prolog",
  "yap": "Prolog",
  "pml": "Promela",
  "spin": "Propeller Spin",
  "proto": "Protocol Buffer",
  "textproto": "Protocol Buffer Text Format",
  "pbtxt": "Protocol Buffer Text Format",
  "txtpb": "Protocol Buffer Text Format",
  "pub": "Public Key",
  "jade": "Pug",
  "pug": "Pug",
  "modulefile": "Puppet",
  "pd": "Pure Data",
  "pb": "PureBasic",
  "pbi": "PureBasic",
  "purs": "PureScript",
  "arr": "Pyret",
  "py": "Python",
  "gyp": "Python",
  "gypi": "Python",
  "lmi": "Python",
  "py3": "Python",
  "pyde": "Python",
  "pyi": "Python",
  "pyp": "Python",
  "pyt": "Python",
  "pyw": "Python",
  "rpy": "Python",
  "spec": "Ruby",
  "tac": "Python",
  "wsgi": "Python",
  "xpy": "Python",
  "gclient": "Python",
  "deps": "Python",
  "sconscript": "Python",
  "sconstruct": "Python",
  "wscript": "Python",
  "pytb": "Python traceback",
  "qs": "Q#",
  "qml": "QML",
  "qbs": "QML",
  "pri": "QMake",
  "installscript.qs": "Qt Script",
  "toolchain_installscript.qs": "Qt Script",
  "m3makefile": "Quake",
  "m3overrides": "Quake",
  "qc": "QuakeC",
  "sip": "SIP",
  "qnt": "Quint",
  "r": "R",
  "rd": "R",
  "rhistory": "R",
  "rsx": "R",
  "rapp.history": "R",
  "rprofile": "R",
  "expr-dist": "R",
  "raml": "RAML",
  "rascript": "RAScript",
  "rbs": "RBS",
  "rdoc": "RDoc",
  "rbbas": "REALbasic",
  "rbfrm": "REALbasic",
  "rbmnu": "REALbasic",
  "rbres": "REALbasic",
  "rbtbar": "REALbasic",
  "rbuistate": "REALbasic",
  "rexx": "REXX",
  "pprx": "REXX",
  "rex": "REXX",
  "qmd": "RMarkdown",
  "rmd": "RMarkdown",
  "ron": "RON",
  "action": "ROS Interface",
  "srv": "ROS Interface",
  "rpgle": "RPGLE",
  "sqlrpgle": "RPGLE",
  "rnh": "RUNOFF",
  "rno": "Roff",
  "rkt": "Racket",
  "rktd": "Racket",
  "rktl": "Racket",
  "scrbl": "Racket",
  "rl": "Ragel",
  "6pl": "Raku",
  "6pm": "Raku",
  "nqp": "Raku",
  "p6": "Raku",
  "p6l": "Raku",
  "p6m": "Raku",
  "pl6": "Raku",
  "pm6": "Raku",
  "raku": "Raku",
  "rakumod": "Raku",
  "rsc": "Rascal",
  "raw": "Raw token data",
  "res": "XML",
  "resi": "ReScript",
  "inputrc": "Readline Config",
  "rei": "Reason",
  "religo": "ReasonLIGO",
  "reb": "Rebol",
  "r2": "Rebol",
  "r3": "Rebol",
  "rebol": "Rebol",
  "language-subtag-registry.txt": "Record Jar",
  "red": "Red",
  "reds": "Red",
  "cw": "Redcode",
  "_redirects": "Redirect Rules",
  "regexp": "Regular Expression",
  "regex": "Regular Expression",
  "rs": "Rust",
  "rsh": "RenderScript",
  "rhai": "Rhai",
  "rtf": "Rich Text Format",
  "ring": "Ring",
  "riot": "Riot",
  "robot": "RobotFramework",
  "resource": "RobotFramework",
  "robots.txt": "Robots Exclusion Rules",
  "roc": "Roc",
  "v": "V",
  "coq": "Rocq Prover",
  "roff": "Roff",
  "1": "Roff",
  "1in": "Roff",
  "1m": "Roff",
  "1x": "Roff",
  "2": "Roff",
  "3": "Roff",
  "3in": "Roff",
  "3m": "Roff",
  "3p": "Roff",
  "3pm": "Roff",
  "3qt": "Roff",
  "3x": "Roff",
  "4": "Roff",
  "5": "Roff",
  "6": "Roff",
  "7": "Roff",
  "8": "Roff",
  "9": "Roff",
  "man": "Roff",
  "mdoc": "Roff",
  "me": "Roff",
  "tmac": "Roff",
  "eqnrc": "Roff",
  "mmn": "Roff",
  "mmt": "Roff",
  "troffrc": "Roff",
  "troffrc-end": "Roff",
  "rg": "Rouge",
  "rb": "Ruby",
  "builder": "Ruby",
  "eye": "Ruby",
  "gemspec": "Ruby",
  "god": "Ruby",
  "jbuilder": "Ruby",
  "mspec": "Ruby",
  "pluginspec": "XML",
  "podspec": "Ruby",
  "prawn": "Ruby",
  "rabl": "Ruby",
  "rake": "Ruby",
  "rbi": "Ruby",
  "rbuild": "Ruby",
  "rbw": "Ruby",
  "rbx": "Ruby",
  "ru": "Ruby",
  "ruby": "Ruby",
  "thor": "Ruby",
  "watchr": "Ruby",
  "irbrc": "Ruby",
  "pryrc": "Ruby",
  "simplecov": "Ruby",
  "appraisals": "Ruby",
  "berksfile": "Ruby",
  "brewfile": "Ruby",
  "buildfile": "Ruby",
  "capfile": "Ruby",
  "dangerfile": "Ruby",
  "deliverfile": "Ruby",
  "fastfile": "Ruby",
  "gemfile": "Ruby",
  "guardfile": "Ruby",
  "jarfile": "Ruby",
  "mavenfile": "Ruby",
  "podfile": "Ruby",
  "puppetfile": "Ruby",
  "rakefile": "Ruby",
  "snapfile": "Ruby",
  "steepfile": "Ruby",
  "thorfile": "Ruby",
  "vagrantfile": "Ruby",
  "rs.in": "Rust",
  "sas": "SAS",
  "scss": "SCSS",
  "te": "SELinux Policy",
  "file_contexts": "SELinux Policy",
  "genfs_contexts": "SELinux Policy",
  "initial_sids": "SELinux Policy",
  "port_contexts": "SELinux Policy",
  "security_classes": "SELinux Policy",
  "smt2": "SMT",
  "smt": "SMT",
  "z3": "SMT",
  "sparql": "SPARQL",
  "rq": "SPARQL",
  "sqf": "SQF",
  "hqf": "SQF",
  "mysql": "SQL",
  "tab": "SQL",
  "udf": "SQL",
  "viw": "SQL",
  "db2": "SQLPL",
  "srt": "SubRip Text",
  "ssh-config": "SSH Config",
  "ssh_config": "SSH Config",
  "sshconfig": "SSH Config",
  "sshconfig.snip": "SSH Config",
  "sshd-config": "SSH Config",
  "sshd_config": "SSH Config",
  "star": "STAR",
  "stl": "STL",
  "ston": "STON",
  "svg": "SVG",
  "swg": "SWIG",
  "swig": "SWIG",
  "sage": "Sage",
  "sagews": "Sage",
  "sail": "Sail",
  "sls": "Salt",
  "sass": "Sass",
  "scala": "Scala",
  "kojo": "Scala",
  "sbt": "Scala",
  "sc": "Scala",
  "scaml": "Scaml",
  "scenic": "Scenic",
  "scm": "Scheme",
  "sld": "Scheme",
  "sps": "Scheme",
  "ss": "Scheme",
  "sci": "Scilab",
  "sce": "Scilab",
  "self": "Self",
  "sh": "Shell",
  "bash": "Shell",
  "bats": "Shell",
  "command": "Shell",
  "ksh": "Shell",
  "pacscript": "Shell",
  "sbatch": "Shell",
  "sh.in": "Shell",
  "slurm": "Shell",
  "tmux": "Shell",
  "tool": "Shell",
  "zsh": "Shell",
  "zsh-theme": "Shell",
  "bash_aliases": "Shell",
  "bash_functions": "Shell",
  "bash_history": "Shell",
  "bash_logout": "Shell",
  "bash_profile": "Shell",
  "bashrc": "Shell",
  "cshrc": "Shell",
  "envrc": "Shell",
  "flaskenv": "Shell",
  "kshrc": "Shell",
  "login": "Shell",
  "profile": "Shell",
  "tmux.conf": "Shell",
  "xinitrc": "Shell",
  "xsession": "Shell",
  "zlogin": "Shell",
  "zlogout": "Shell",
  "zprofile": "Shell",
  "zshenv": "Shell",
  "zshrc": "Shell",
  "9fs": "Shell",
  "pkgbuild": "Shell",
  "gradlew": "Shell",
  "mvnw": "Shell",
  "shellcheckrc": "ShellCheck Config",
  "sh-session": "ShellSession",
  "shen": "Shen",
  "sieve": "Sieve",
  "sfv": "Simple File Verification",
  "singularity": "Singularity",
  "slang": "Slang",
  "sl": "Slash",
  "slim": "Slim",
  "slint": "Slint",
  "cocci": "SmPL",
  "smali": "Smali",
  "st": "Smalltalk",
  "smithy": "Smithy",
  "smk": "Snakemake",
  "snakefile": "Snakemake",
  "android.bp": "Soong",
  "sp": "SourcePawn",
  "zed": "SpiceDB Schema",
  "sfd": "Spline Font Database",
  "nut": "Squirrel",
  "stan": "Stan",
  "fun": "Standard ML",
  "sig": "Standard ML",
  "sml": "Standard ML",
  "bzl": "Starlark",
  "buck": "Starlark",
  "build": "Starlark",
  "build.bazel": "Starlark",
  "module.bazel": "Starlark",
  "tiltfile": "Starlark",
  "workspace": "Starlark",
  "workspace.bazel": "Starlark",
  "workspace.bzlmod": "Starlark",
  "do": "Stata",
  "ado": "Stata",
  "doh": "Stata",
  "ihlp": "Stata",
  "mata": "Stata",
  "matah": "Stata",
  "sthlp": "Stata",
  "styl": "Stylus",
  "sss": "SugarSS",
  "surql": "SurrealQL",
  "svx": "mdsvex",
  "svelte": "Svelte",
  "sw": "XML",
  "rnw": "Sweave",
  "swift": "Swift",
  "sv": "SystemVerilog",
  "svh": "SystemVerilog",
  "vh": "SystemVerilog",
  "8xp": "TI Program",
  "8xp.txt": "TI Program",
  "tlv": "TL-Verilog",
  "tla": "TLA",
  "tmdl": "TMDL",
  "toml": "TOML",
  "toml.example": "TOML",
  "cargo.lock": "TOML",
  "cargo.toml.orig": "TOML",
  "gopkg.lock": "TOML",
  "pipfile": "TOML",
  "mise.local.lock": "TOML",
  "mise.lock": "TOML",
  "pdm.lock": "TOML",
  "poetry.lock": "TOML",
  "uv.lock": "TOML",
  "tsp": "TypeSpec",
  "tsv": "TSV",
  "vcf": "TSV",
  "tsx": "TypeScript",
  "txl": "TXL",
  "talon": "Talon",
  "tape": "Tape",
  "tcl": "Tcl",
  "adp": "Tcl",
  "sdc": "Tcl",
  "tcl.in": "Tcl",
  "tm": "Tcl",
  "xdc": "Tcl",
  "owh": "Tcl",
  "starfield": "Tcl",
  "tcsh": "Tcsh",
  "csh": "Tcsh",
  "tex": "TeX",
  "aux": "TeX",
  "bbx": "TeX",
  "cbx": "TeX",
  "dtx": "TeX",
  "ins": "TeX",
  "lbx": "TeX",
  "ltx": "TeX",
  "mkii": "TeX",
  "mkiv": "TeX",
  "mkvi": "TeX",
  "sty": "TeX",
  "toc": "TeX",
  "tea": "Tea",
  "tl": "Teal",
  "tftpl": "Terraform Template",
  "texinfo": "Texinfo",
  "texi": "Texinfo",
  "txi": "Texinfo",
  "nb": "Text",
  "no": "Text",
  "citation": "Text",
  "citations": "Text",
  "copying": "Text",
  "copying.regex": "Text",
  "copyright.regex": "Text",
  "fontlog": "Text",
  "install": "Text",
  "install.mysql": "Text",
  "license": "Text",
  "license.mysql": "Text",
  "news": "Text",
  "readme.me": "Text",
  "readme.mysql": "Text",
  "readme.nss": "Text",
  "readme.pc": "Text",
  "click.me": "Text",
  "delete.me": "Text",
  "keep.me": "Text",
  "package.mask": "Text",
  "package.use.mask": "Text",
  "package.use.stable.mask": "Text",
  "read.me": "Text",
  "readme.1st": "Text",
  "test.me": "Text",
  "use.mask": "Text",
  "use.stable.mask": "Text",
  "textgrid": "TextGrid",
  "tm_properties": "TextMate Properties",
  "textile": "Textile",
  "thrift": "Thrift",
  "toit": "Toit",
  "tolk": "Tolk",
  "torrc": "Tor Config",
  "tu": "Turing",
  "ttl": "Turtle",
  "twig": "Twig",
  "ts": "TypeScript",
  "cts": "TypeScript",
  "mts": "TypeScript",
  "typ": "XML",
  "upc": "Unified Parallel C",
  "anim": "Unity3D Asset",
  "asset": "Unity3D Asset",
  "mat": "Unity3D Asset",
  "meta": "Unity3D Asset",
  "prefab": "Unity3D Asset",
  "unity": "Unity3D Asset",
  "uno": "Uno",
  "uc": "ucode",
  "uplc": "Untyped Plutus Core",
  "ur": "UrWeb",
  "urs": "UrWeb",
  "vba": "VBA",
  "vbs": "VBScript",
  "vcl": "VCL",
  "vhdl": "VHDL",
  "vhd": "VHDL",
  "vhf": "VHDL",
  "vhi": "VHDL",
  "vho": "VHDL",
  "vhs": "VHDL",
  "vht": "VHDL",
  "vhw": "VHDL",
  "vala": "Vala",
  "vapi": "Vala",
  "vdf": "Valve Data Format",
  "vmf": "Valve Data Format",
  "vtl": "Velocity Template Language",
  "vto": "Vento",
  "veo": "Verilog",
  "verse": "Verse",
  "sd": "Vespa Schema Definition",
  "snip": "Vim Snippet",
  "snippet": "Vim Snippet",
  "snippets": "Vim Snippet",
  "vim": "Vim script",
  "vimrc": "Vim script",
  "vmb": "Vim script",
  "exrc": "Vim script",
  "gvimrc": "Vim script",
  "nvimrc": "Vim script",
  "_vimrc": "Vim script",
  "vb": "Visual Basic .NET",
  "vbhtml": "Visual Basic .NET",
  "ctl": "Visual Basic 6.0",
  "dsr": "Visual Basic 6.0",
  "volt": "Volt",
  "vue": "Vue",
  "vy": "Vyper",
  "wdl": "WDL",
  "wgsl": "WGSL",
  "mtl": "Wavefront Material",
  "obj": "Wavefront Object",
  "owl": "Web Ontology Language",
  "wast": "WebAssembly",
  "wat": "WebAssembly",
  "wit": "WebAssembly Interface Type",
  "webidl": "WebIDL",
  "vtt": "WebVTT",
  "wgetrc": "Wget Config",
  "whiley": "Whiley",
  "mediawiki": "Wikitext",
  "wiki": "Wikitext",
  "wikitext": "Wikitext",
  "reg": "Windows Registry Entries",
  "ws": "Witcher Script",
  "mathematica": "Wolfram Language",
  "cdf": "Wolfram Language",
  "ma": "Wolfram Language",
  "mt": "Wolfram Language",
  "nbp": "Wolfram Language",
  "wl": "Wolfram Language",
  "wls": "Wolfram Language",
  "wlt": "Wolfram Language",
  "wlk": "Wollok",
  "wren": "Wren",
  "xbm": "X BitMap",
  "encodings.dir": "X Font Directory Index",
  "fonts.alias": "X Font Directory Index",
  "fonts.dir": "X Font Directory Index",
  "fonts.scale": "X Font Directory Index",
  "xpm": "X PixMap",
  "x10": "X10",
  "xc": "XC",
  "xcompose": "XCompose",
  "xml": "XML",
  "adml": "XML",
  "admx": "XML",
  "ant": "XML",
  "axaml": "XML",
  "axml": "XML",
  "builds": "XML",
  "ccproj": "XML",
  "ccxml": "XML",
  "clixml": "XML",
  "cproject": "XML",
  "cscfg": "XML",
  "csdef": "XML",
  "csproj": "XML",
  "ct": "XML",
  "depproj": "XML",
  "dita": "XML",
  "ditamap": "XML",
  "ditaval": "XML",
  "dll.config": "XML",
  "dotsettings": "XML",
  "filters": "XML",
  "fsproj": "XML",
  "fxml": "XML",
  "glade": "XML",
  "gmx": "XML",
  "gpx": "XML",
  "grxml": "XML",
  "hzp": "XML",
  "icls": "XML",
  "iml": "XML",
  "ivy": "XML",
  "jelly": "XML",
  "jsproj": "XML",
  "kml": "XML",
  "launch": "XML",
  "mdpolicy": "XML",
  "meta4": "XML",
  "mjml": "XML",
  "mxml": "XML",
  "natvis": "XML",
  "ndproj": "XML",
  "nproj": "XML",
  "nuspec": "XML",
  "odd": "XML",
  "osm": "XML",
  "pkgproj": "XML",
  "proj": "XML",
  "props": "XML",
  "ps1xml": "XML",
  "psc1": "XML",
  "pt": "XML",
  "pubxml": "XML",
  "qhelp": "XML",
  "rbxmx": "XML",
  "rdf": "XML",
  "resx": "XML",
  "rss": "XML",
  "scxml": "XML",
  "sfproj": "XML",
  "shproj": "XML",
  "slnx": "XML",
  "srdf": "XML",
  "storyboard": "XML",
  "sublime-snippet": "XML",
  "targets": "XML",
  "tml": "XML",
  "ui": "XML",
  "urdf": "XML",
  "ux": "XML",
  "vbproj": "XML",
  "vcxproj": "XML",
  "vsixmanifest": "XML",
  "vssettings": "XML",
  "vstemplate": "XML",
  "vxml": "XML",
  "wixproj": "XML",
  "wsdl": "XML",
  "wsf": "XML",
  "wxi": "XML",
  "wxl": "XML",
  "wxs": "XML",
  "x3d": "XML",
  "xacro": "XML",
  "xaml": "XML",
  "xib": "XML",
  "xlf": "XML",
  "xliff": "XML",
  "xmi": "XML",
  "xml.dist": "XML",
  "xmp": "XML",
  "xproj": "XML",
  "xsd": "XML",
  "xspec": "XML",
  "xul": "XML",
  "zcml": "XML",
  "classpath": "XML",
  "project": "XML",
  "app.config": "XML",
  "nuget.config": "XML",
  "settings.stylecop": "XML",
  "web.debug.config": "XML",
  "web.release.config": "XML",
  "web.config": "XML",
  "packages.config": "XML",
  "sttheme": "XML Property List",
  "tmcommand": "XML Property List",
  "tmlanguage": "XML Property List",
  "tmpreferences": "XML Property List",
  "tmsnippet": "XML Property List",
  "tmtheme": "XML Property List",
  "xsp-config": "XPages",
  "xsp.metadata": "XPages",
  "xpl": "XProc",
  "xproc": "XProc",
  "xquery": "XQuery",
  "xq": "XQuery",
  "xql": "XQuery",
  "xqm": "XQuery",
  "xqy": "XQuery",
  "xs": "XS",
  "xslt": "XSLT",
  "xsl": "XSLT",
  "xmake.lua": "Xmake",
  "xojo_code": "Xojo",
  "xojo_menu": "Xojo",
  "xojo_report": "Xojo",
  "xojo_script": "Xojo",
  "xojo_toolbar": "Xojo",
  "xojo_window": "Xojo",
  "xsh": "Xonsh",
  "xtend": "Xtend",
  "mir": "YAML",
  "reek": "YAML",
  "rviz": "YAML",
  "sublime-syntax": "YAML",
  "syntax": "YAML",
  "yaml-tmlanguage": "YAML",
  "yaml.sed": "YAML",
  "yml.mysql": "YAML",
  "clang-format": "YAML",
  "clang-tidy": "YAML",
  "clangd": "YAML",
  "gemrc": "YAML",
  "citation.cff": "YAML",
  "glide.lock": "YAML",
  "pixi.lock": "YAML",
  "yarn.lock": "YAML",
  "yang": "YANG",
  "yar": "YARA",
  "yara": "YARA",
  "yasnippet": "YASnippet",
  "y": "Yacc",
  "yacc": "Yacc",
  "yul": "Yul",
  "zap": "ZAP",
  "xzap": "ZAP",
  "zil": "ZIL",
  "mud": "ZIL",
  "zeek": "Zeek",
  "bro": "Zeek",
  "zs": "ZenScript",
  "zep": "Zephir",
  "zig": "Zig",
  "zig.zon": "Zig",
  "zimpl": "Zimpl",
  "zmpl": "Zimpl",
  "zpl": "Zimpl",
  "zmodel": "Zmodel",
  "curlrc": "cURL Config",
  "_curlrc": "cURL Config",
  "crontab": "crontab",
  "desktop": "desktop",
  "desktop.in": "desktop",
  "dircolors": "dircolors",
  "dir_colors": "dircolors",
  "_dir_colors": "dircolors",
  "_dircolors": "dircolors",
  "ec": "eC",
  "eh": "eC",
  "edn": "edn",
  "fish": "fish",
  "hoon": "hoon",
  "ics": "iCalendar",
  "ical": "iCalendar",
  "kv": "kvlang",
  "mrc": "mIRC Script",
  "mcfunction": "mcfunction",
  "mu": "mupad",
  "nanorc": "nanorc",
  "nc": "nesC",
  "ooc": "ooc",
  "pc.in": "pkg-config",
  "rst": "reStructuredText",
  "rest": "reStructuredText",
  "rest.txt": "reStructuredText",
  "rst.txt": "reStructuredText",
  "sed": "sed",
  "templ": "templ",
  "wisp": "wisp",
  "prg": "xBase",
  "prw": "xBase"
};

export const LANGUAGE_TYPE: Record<string, string> = {
  "1C Enterprise": "programming",
  "2-Dimensional Array": "data",
  "4D": "programming",
  "ABAP": "programming",
  "ABAP CDS": "programming",
  "ABNF": "data",
  "AGS Script": "programming",
  "AIDL": "programming",
  "AL": "programming",
  "ALGOL": "programming",
  "AMPL": "programming",
  "ANTLR": "programming",
  "API Blueprint": "markup",
  "APL": "programming",
  "ASL": "programming",
  "ASN.1": "data",
  "ASP.NET": "programming",
  "ATS": "programming",
  "ActionScript": "programming",
  "Ada": "programming",
  "Adblock Filter List": "data",
  "Adobe Font Metrics": "data",
  "Agda": "programming",
  "Aiken": "programming",
  "Aleo": "programming",
  "Alloy": "programming",
  "Alpine Abuild": "programming",
  "Altium Designer": "data",
  "AngelScript": "programming",
  "Answer Set Programming": "programming",
  "Ant Build System": "data",
  "Antlers": "markup",
  "ApacheConf": "data",
  "Apex": "programming",
  "Apollo Guidance Computer": "programming",
  "AppleScript": "programming",
  "Arc": "programming",
  "AsciiDoc": "prose",
  "AspectJ": "programming",
  "Assembly": "programming",
  "Astro": "markup",
  "Asymptote": "programming",
  "Augeas": "programming",
  "AutoHotkey": "programming",
  "AutoIt": "programming",
  "Avro IDL": "data",
  "Awk": "programming",
  "B": "programming",
  "B (Formal Method)": "programming",
  "B4X": "programming",
  "BAML": "programming",
  "BASIC": "programming",
  "BBCode": "markup",
  "BIRD2": "data",
  "BQN": "programming",
  "Ballerina": "programming",
  "Batchfile": "programming",
  "Beef": "programming",
  "Befunge": "programming",
  "Berry": "programming",
  "BibTeX": "markup",
  "BibTeX Style": "programming",
  "Bicep": "programming",
  "Bikeshed": "markup",
  "Bison": "programming",
  "BitBake": "programming",
  "Blade": "markup",
  "BlitzBasic": "programming",
  "BlitzMax": "programming",
  "Blueprint": "markup",
  "Bluespec": "programming",
  "Bluespec BH": "programming",
  "Boo": "programming",
  "Boogie": "programming",
  "Brainfuck": "programming",
  "BrighterScript": "programming",
  "Brightscript": "programming",
  "Browserslist": "data",
  "Bru": "markup",
  "BuildStream": "data",
  "C": "programming",
  "C#": "programming",
  "C++": "programming",
  "C-ObjDump": "data",
  "C2hs Haskell": "programming",
  "C3": "programming",
  "CAP CDS": "programming",
  "CIL": "data",
  "CLIPS": "programming",
  "CMake": "programming",
  "COBOL": "programming",
  "CODEOWNERS": "data",
  "COLLADA": "data",
  "CQL": "programming",
  "CSON": "data",
  "CSS": "markup",
  "CSV": "data",
  "CUE": "programming",
  "CWeb": "programming",
  "Cabal Config": "data",
  "Caddyfile": "data",
  "Cadence": "programming",
  "Cairo": "programming",
  "Cairo Zero": "programming",
  "CameLIGO": "programming",
  "Cangjie": "programming",
  "Cap'n Proto": "programming",
  "Carbon": "programming",
  "CartoCSS": "programming",
  "Ceylon": "programming",
  "Chapel": "programming",
  "Charity": "programming",
  "Checksums": "data",
  "ChucK": "programming",
  "Circom": "programming",
  "Cirru": "programming",
  "Clarion": "programming",
  "Clarity": "programming",
  "Classic ASP": "programming",
  "Clean": "programming",
  "Click": "programming",
  "Clojure": "programming",
  "Closure Templates": "markup",
  "Cloud Firestore Security Rules": "data",
  "Clue": "programming",
  "CoNLL-U": "data",
  "CodeQL": "programming",
  "CoffeeScript": "programming",
  "ColdFusion": "programming",
  "ColdFusion CFC": "programming",
  "Common Lisp": "programming",
  "Common Workflow Language": "programming",
  "Component Pascal": "programming",
  "Cooklang": "markup",
  "Cool": "programming",
  "Cpp-ObjDump": "data",
  "Creole": "prose",
  "Crystal": "programming",
  "Csound": "programming",
  "Csound Document": "programming",
  "Csound Score": "programming",
  "Cuda": "programming",
  "Cue Sheet": "data",
  "Curry": "programming",
  "Cycript": "programming",
  "Cylc": "data",
  "Cypher": "programming",
  "Cython": "programming",
  "D": "programming",
  "D-ObjDump": "data",
  "D2": "markup",
  "DIGITAL Command Language": "programming",
  "DM": "programming",
  "DNS Zone": "data",
  "DTrace": "programming",
  "Dafny": "programming",
  "Darcs Patch": "data",
  "Dart": "programming",
  "Daslang": "programming",
  "DataWeave": "programming",
  "Debian Package Control File": "data",
  "DenizenScript": "programming",
  "Dhall": "programming",
  "Diff": "data",
  "DirectX 3D File": "data",
  "Dockerfile": "programming",
  "Dogescript": "programming",
  "Dotenv": "data",
  "Dune": "programming",
  "Dylan": "programming",
  "E": "programming",
  "E-mail": "data",
  "EBNF": "data",
  "ECL": "programming",
  "ECLiPSe": "programming",
  "EJS": "markup",
  "EQ": "programming",
  "Eagle": "data",
  "Earthly": "programming",
  "Easybuild": "data",
  "Ecere Projects": "data",
  "Ecmarkup": "markup",
  "Edge": "markup",
  "EdgeQL": "programming",
  "EditorConfig": "data",
  "Edje Data Collection": "data",
  "Eiffel": "programming",
  "Elixir": "programming",
  "Elm": "programming",
  "Elvish": "programming",
  "Elvish Transcript": "programming",
  "Emacs Lisp": "programming",
  "EmberScript": "programming",
  "Erlang": "programming",
  "Euphoria": "programming",
  "F#": "programming",
  "F*": "programming",
  "FIGlet Font": "data",
  "FIRRTL": "programming",
  "FLUX": "programming",
  "FPP": "programming",
  "Factor": "programming",
  "Fancy": "programming",
  "Fantom": "programming",
  "Faust": "programming",
  "Fennel": "programming",
  "Filebench WML": "programming",
  "Filterscript": "programming",
  "FlatBuffers": "data",
  "Flix": "programming",
  "Fluent": "programming",
  "Formatted": "data",
  "Forth": "programming",
  "Fortran": "programming",
  "Fortran Free Form": "programming",
  "FreeBASIC": "programming",
  "FreeMarker": "programming",
  "Frege": "programming",
  "Futhark": "programming",
  "G-code": "programming",
  "GAML": "programming",
  "GAMS": "programming",
  "GAP": "programming",
  "GCC Machine Description": "programming",
  "GDB": "programming",
  "GDScript": "programming",
  "GDShader": "programming",
  "GEDCOM": "data",
  "GLSL": "programming",
  "GN": "data",
  "GSC": "programming",
  "Game Maker Language": "programming",
  "Gemfile.lock": "data",
  "Gemini": "prose",
  "Genero 4gl": "programming",
  "Genero per": "markup",
  "Genie": "programming",
  "Genshi": "programming",
  "Gentoo Ebuild": "programming",
  "Gentoo Eclass": "programming",
  "Gerber Image": "data",
  "Gettext Catalog": "prose",
  "Gherkin": "programming",
  "Git Attributes": "data",
  "Git Commit": "data",
  "Git Config": "data",
  "Git Revision List": "data",
  "Gleam": "programming",
  "Glimmer JS": "programming",
  "Glimmer TS": "programming",
  "Glyph": "programming",
  "Glyph Bitmap Distribution Format": "data",
  "Gno": "programming",
  "Gnuplot": "programming",
  "Go": "programming",
  "Go Checksums": "data",
  "Go Module": "data",
  "Go Template": "markup",
  "Go Workspace": "data",
  "Godot Resource": "data",
  "Golo": "programming",
  "Gosu": "programming",
  "Grace": "programming",
  "Gradle": "data",
  "Gradle Kotlin DSL": "data",
  "Grammatical Framework": "programming",
  "Graph Modeling Language": "data",
  "GraphQL": "data",
  "Graphviz (DOT)": "data",
  "Groovy": "programming",
  "Groovy Server Pages": "programming",
  "GtkRC": "data",
  "HAProxy": "data",
  "HCL": "programming",
  "HIP": "programming",
  "HLSL": "programming",
  "HOCON": "data",
  "HTML": "markup",
  "HTML+ECR": "markup",
  "HTML+EEX": "markup",
  "HTML+ERB": "markup",
  "HTML+PHP": "markup",
  "HTML+Razor": "markup",
  "HTTP": "data",
  "HXML": "data",
  "Hack": "programming",
  "Haml": "markup",
  "Handlebars": "markup",
  "Harbour": "programming",
  "Hare": "programming",
  "Haskell": "programming",
  "Haxe": "programming",
  "HiveQL": "programming",
  "HolyC": "programming",
  "Hosts File": "data",
  "Hurl": "programming",
  "Hy": "programming",
  "HyPhy": "programming",
  "IDL": "programming",
  "IGOR Pro": "programming",
  "IL Assembly": "programming",
  "INI": "data",
  "IRC log": "data",
  "ISPC": "programming",
  "Idris": "programming",
  "Ignore List": "data",
  "ImHex Pattern Language": "programming",
  "ImageJ Macro": "programming",
  "Imba": "programming",
  "Inform 7": "programming",
  "Ink": "programming",
  "Inno Setup": "programming",
  "Io": "programming",
  "Ioke": "programming",
  "Isabelle": "programming",
  "Isabelle ROOT": "programming",
  "J": "programming",
  "JAR Manifest": "data",
  "JASS": "programming",
  "JCL": "programming",
  "JFlex": "programming",
  "JSON": "data",
  "JSON with Comments": "data",
  "JSON5": "data",
  "JSONLD": "data",
  "JSONiq": "programming",
  "Jac": "programming",
  "Jai": "programming",
  "Janet": "programming",
  "Jasmin": "programming",
  "Java": "programming",
  "Java Properties": "data",
  "Java Server Pages": "programming",
  "Java Template Engine": "programming",
  "JavaScript": "programming",
  "JavaScript+ERB": "programming",
  "Jest Snapshot": "data",
  "JetBrains MPS": "programming",
  "Jinja": "markup",
  "Jison": "programming",
  "Jison Lex": "programming",
  "Jolie": "programming",
  "Jsonnet": "programming",
  "Julia": "programming",
  "Julia REPL": "programming",
  "Jupyter Notebook": "markup",
  "Just": "programming",
  "KCL": "programming",
  "KDL": "data",
  "KFramework": "programming",
  "KRL": "programming",
  "Kaitai Struct": "programming",
  "KakouneScript": "programming",
  "KerboScript": "programming",
  "KiCad Layout": "data",
  "KiCad Legacy Layout": "data",
  "KiCad Schematic": "data",
  "Kickstart": "data",
  "Kit": "markup",
  "KoLmafia ASH": "programming",
  "Koka": "programming",
  "Kotlin": "programming",
  "Kusto": "data",
  "LFE": "programming",
  "LLVM": "programming",
  "LOLCODE": "programming",
  "LSL": "programming",
  "LTspice Symbol": "data",
  "LabVIEW": "programming",
  "Lambdapi": "programming",
  "Langium": "programming",
  "Lark": "data",
  "Lasso": "programming",
  "Latte": "markup",
  "Lean": "programming",
  "Lean 4": "programming",
  "Leo": "programming",
  "Less": "markup",
  "Lex": "programming",
  "LigoLANG": "programming",
  "LilyPond": "programming",
  "Limbo": "programming",
  "Linear Programming": "programming",
  "Linker Script": "programming",
  "Linux Kernel Module": "data",
  "Liquid": "markup",
  "Liquidsoap": "programming",
  "Literate Agda": "programming",
  "Literate CoffeeScript": "programming",
  "Literate Haskell": "programming",
  "LiveCode Script": "programming",
  "LiveScript": "programming",
  "Lobster": "programming",
  "Logos": "programming",
  "Logtalk": "programming",
  "LookML": "programming",
  "LoomScript": "programming",
  "Lua": "programming",
  "Luau": "programming",
  "M": "programming",
  "M3U": "data",
  "M4": "programming",
  "M4Sugar": "programming",
  "MATLAB": "programming",
  "MAXScript": "programming",
  "MDX": "markup",
  "MLIR": "programming",
  "MQL4": "programming",
  "MQL5": "programming",
  "MTML": "markup",
  "MUF": "programming",
  "Macaulay2": "programming",
  "Makefile": "programming",
  "Mako": "programming",
  "Markdown": "prose",
  "Marko": "markup",
  "Mask": "markup",
  "Mathematical Programming System": "programming",
  "Maven POM": "data",
  "Max": "programming",
  "MeTTa": "programming",
  "Mercury": "programming",
  "Mermaid": "markup",
  "Meson": "programming",
  "Metal": "programming",
  "Microsoft Developer Studio Project": "data",
  "Microsoft Visual Studio Solution": "data",
  "MiniD": "programming",
  "MiniScript": "programming",
  "MiniYAML": "data",
  "MiniZinc": "programming",
  "MiniZinc Data": "data",
  "Mint": "programming",
  "Mirah": "programming",
  "Modelica": "programming",
  "Modula-2": "programming",
  "Modula-3": "programming",
  "Module Management System": "programming",
  "Mojo": "programming",
  "Monkey": "programming",
  "Monkey C": "programming",
  "Moocode": "programming",
  "MoonBit": "programming",
  "MoonScript": "programming",
  "Motoko": "programming",
  "Motorola 68K Assembly": "programming",
  "Move": "programming",
  "Muse": "prose",
  "Mustache": "markup",
  "Myghty": "programming",
  "NASL": "programming",
  "NCL": "programming",
  "NEON": "data",
  "NL": "data",
  "NMODL": "programming",
  "NPM Config": "data",
  "NSIS": "programming",
  "NWScript": "programming",
  "Nasal": "programming",
  "Nearley": "programming",
  "Nemerle": "programming",
  "NetLinx": "programming",
  "NetLinx+ERB": "programming",
  "NetLogo": "programming",
  "NewLisp": "programming",
  "Nextflow": "programming",
  "Nginx": "data",
  "Nickel": "programming",
  "Nim": "programming",
  "Ninja": "data",
  "Nit": "programming",
  "Nix": "programming",
  "Noir": "programming",
  "Nu": "programming",
  "NumPy": "programming",
  "Nunjucks": "markup",
  "Nushell": "programming",
  "OASv2-json": "data",
  "OASv2-yaml": "data",
  "OASv3-json": "data",
  "OASv3-yaml": "data",
  "OCaml": "programming",
  "OMNeT++ MSG": "programming",
  "OMNeT++ NED": "programming",
  "Oberon": "programming",
  "ObjDump": "data",
  "Object Data Instance Notation": "data",
  "ObjectScript": "programming",
  "Objective-C": "programming",
  "Objective-C++": "programming",
  "Objective-J": "programming",
  "Odin": "programming",
  "Omgrofl": "programming",
  "Opa": "programming",
  "Opal": "programming",
  "Open Policy Agent": "programming",
  "OpenAPI Specification v2": "data",
  "OpenAPI Specification v3": "data",
  "OpenCL": "programming",
  "OpenEdge ABL": "programming",
  "OpenQASM": "programming",
  "OpenRC runscript": "programming",
  "OpenSCAD": "programming",
  "OpenStep Property List": "data",
  "OpenType Feature File": "data",
  "Option List": "data",
  "Org": "prose",
  "OverPy": "programming",
  "OverpassQL": "programming",
  "Ox": "programming",
  "Oxygene": "programming",
  "Oz": "programming",
  "P4": "programming",
  "PDDL": "programming",
  "PEG.js": "programming",
  "PHP": "programming",
  "PLSQL": "programming",
  "PLpgSQL": "programming",
  "POV-Ray SDL": "programming",
  "Pact": "programming",
  "Pan": "programming",
  "Papyrus": "programming",
  "Parrot": "programming",
  "Parrot Assembly": "programming",
  "Parrot Internal Representation": "programming",
  "Pascal": "programming",
  "Pawn": "programming",
  "Pep8": "programming",
  "Perl": "programming",
  "Pic": "markup",
  "Pickle": "data",
  "PicoLisp": "programming",
  "PigLatin": "programming",
  "Pike": "programming",
  "Pip Requirements": "data",
  "Pkl": "programming",
  "PlantUML": "data",
  "Pod": "prose",
  "Pod 6": "prose",
  "PogoScript": "programming",
  "Polar": "programming",
  "Pony": "programming",
  "Portugol": "programming",
  "PostCSS": "markup",
  "PostScript": "markup",
  "Power Query": "programming",
  "PowerBuilder": "programming",
  "PowerShell": "programming",
  "Praat": "programming",
  "Prisma": "data",
  "Pro*C": "programming",
  "Processing": "programming",
  "Procfile": "programming",
  "Proguard": "data",
  "Prolog": "programming",
  "Promela": "programming",
  "Propeller Spin": "programming",
  "Protocol Buffer": "data",
  "Protocol Buffer Text Format": "data",
  "Public Key": "data",
  "Pug": "markup",
  "Puppet": "programming",
  "Pure Data": "data",
  "PureBasic": "programming",
  "PureScript": "programming",
  "Pyret": "programming",
  "Python": "programming",
  "Python console": "programming",
  "Python traceback": "data",
  "Q#": "programming",
  "QML": "programming",
  "QMake": "programming",
  "Qt Script": "programming",
  "Quake": "programming",
  "QuakeC": "programming",
  "Quartus Simulation IP": "data",
  "QuickBASIC": "programming",
  "Quint": "programming",
  "R": "programming",
  "RAML": "markup",
  "RAScript": "programming",
  "RBS": "data",
  "RDoc": "prose",
  "REALbasic": "programming",
  "REXX": "programming",
  "RMarkdown": "prose",
  "RON": "data",
  "ROS Interface": "data",
  "RPC": "programming",
  "RPGLE": "programming",
  "RPM Spec": "data",
  "RUNOFF": "markup",
  "Racket": "programming",
  "Ragel": "programming",
  "Raku": "programming",
  "Rascal": "programming",
  "Raw token data": "data",
  "ReScript": "programming",
  "Readline Config": "data",
  "Reason": "programming",
  "ReasonLIGO": "programming",
  "Rebol": "programming",
  "Record Jar": "data",
  "Red": "programming",
  "Redcode": "programming",
  "Redirect Rules": "data",
  "Redscript": "programming",
  "Regular Expression": "data",
  "Ren'Py": "programming",
  "RenderScript": "programming",
  "Rez": "programming",
  "Rhai": "programming",
  "Rich Text Format": "markup",
  "Ring": "programming",
  "Riot": "markup",
  "RobotFramework": "programming",
  "Robots Exclusion Rules": "data",
  "Roc": "programming",
  "Rocq Prover": "programming",
  "Roff": "markup",
  "Roff Manpage": "markup",
  "Rouge": "programming",
  "RouterOS Script": "programming",
  "Ruby": "programming",
  "Rust": "programming",
  "SAS": "programming",
  "SCSS": "markup",
  "SELinux Policy": "data",
  "SIP": "programming",
  "SMT": "programming",
  "SPARQL": "data",
  "SQF": "programming",
  "SQL": "data",
  "SQLPL": "programming",
  "SRecode Template": "markup",
  "SSH Config": "data",
  "STAR": "data",
  "STL": "data",
  "STON": "data",
  "SVG": "data",
  "SWIG": "programming",
  "Sage": "programming",
  "Sail": "programming",
  "Salt": "programming",
  "Sass": "markup",
  "Scala": "programming",
  "Scaml": "markup",
  "Scenic": "programming",
  "Scheme": "programming",
  "Scilab": "programming",
  "Self": "programming",
  "ShaderLab": "programming",
  "Shell": "programming",
  "ShellCheck Config": "data",
  "ShellSession": "programming",
  "Shen": "programming",
  "Sieve": "programming",
  "Simple File Verification": "data",
  "Singularity": "programming",
  "Slang": "programming",
  "Slash": "programming",
  "Slice": "programming",
  "Slim": "markup",
  "Slint": "markup",
  "SmPL": "programming",
  "Smali": "programming",
  "Smalltalk": "programming",
  "Smarty": "programming",
  "Smithy": "programming",
  "Snakemake": "programming",
  "Solidity": "programming",
  "Soong": "data",
  "SourcePawn": "programming",
  "SpiceDB Schema": "data",
  "Spline Font Database": "data",
  "Squirrel": "programming",
  "Stan": "programming",
  "Standard ML": "programming",
  "Starlark": "programming",
  "Stata": "programming",
  "StringTemplate": "markup",
  "Stylus": "markup",
  "SubRip Text": "data",
  "SugarSS": "markup",
  "SuperCollider": "programming",
  "SurrealQL": "programming",
  "Survex data": "data",
  "Svelte": "markup",
  "Sway": "programming",
  "Sweave": "prose",
  "Swift": "programming",
  "SystemVerilog": "programming",
  "TI Program": "programming",
  "TL-Verilog": "programming",
  "TLA": "programming",
  "TMDL": "data",
  "TOML": "data",
  "TSPLIB data": "data",
  "TSQL": "programming",
  "TSV": "data",
  "TSX": "programming",
  "TXL": "programming",
  "Tact": "programming",
  "Talon": "programming",
  "Tape": "programming",
  "Tcl": "programming",
  "Tcsh": "programming",
  "TeX": "markup",
  "Tea": "markup",
  "Teal": "programming",
  "Terra": "programming",
  "Terraform Template": "markup",
  "Texinfo": "prose",
  "Text": "prose",
  "TextGrid": "data",
  "TextMate Properties": "data",
  "Textile": "prose",
  "Thrift": "programming",
  "Toit": "programming",
  "Tolk": "programming",
  "Tor Config": "data",
  "Tree-sitter Query": "programming",
  "Turing": "programming",
  "Turtle": "data",
  "Twig": "markup",
  "Type Language": "data",
  "TypeScript": "programming",
  "TypeSpec": "programming",
  "Typst": "programming",
  "Unified Parallel C": "programming",
  "Unity3D Asset": "data",
  "Unix Assembly": "programming",
  "Uno": "programming",
  "UnrealScript": "programming",
  "Untyped Plutus Core": "programming",
  "UrWeb": "programming",
  "V": "programming",
  "VBA": "programming",
  "VBScript": "programming",
  "VCL": "programming",
  "VHDL": "programming",
  "Vala": "programming",
  "Valve Data Format": "data",
  "Velocity Template Language": "markup",
  "Vento": "markup",
  "Verilog": "programming",
  "Verse": "programming",
  "Vespa Schema Definition": "data",
  "Vim Help File": "prose",
  "Vim Snippet": "markup",
  "Vim script": "programming",
  "Visual Basic .NET": "programming",
  "Visual Basic 6.0": "programming",
  "Volt": "programming",
  "Vue": "markup",
  "Vyper": "programming",
  "WDL": "programming",
  "WGSL": "programming",
  "Wavefront Material": "data",
  "Wavefront Object": "data",
  "Web Ontology Language": "data",
  "WebAssembly": "programming",
  "WebAssembly Interface Type": "data",
  "WebIDL": "programming",
  "WebVTT": "data",
  "Wget Config": "data",
  "Whiley": "programming",
  "Wikitext": "prose",
  "Win32 Message File": "data",
  "Windows Registry Entries": "data",
  "Witcher Script": "programming",
  "Wolfram Language": "programming",
  "Wollok": "programming",
  "World of Warcraft Addon Data": "data",
  "Wren": "programming",
  "X BitMap": "data",
  "X Font Directory Index": "data",
  "X PixMap": "data",
  "X10": "programming",
  "XC": "programming",
  "XCompose": "data",
  "XML": "data",
  "XML Property List": "data",
  "XPages": "data",
  "XProc": "programming",
  "XQuery": "programming",
  "XS": "programming",
  "XSLT": "programming",
  "Xmake": "programming",
  "Xojo": "programming",
  "Xonsh": "programming",
  "Xtend": "programming",
  "YAML": "data",
  "YANG": "data",
  "YARA": "programming",
  "YASnippet": "markup",
  "Yacc": "programming",
  "Yul": "programming",
  "ZAP": "programming",
  "ZIL": "programming",
  "Zeek": "programming",
  "ZenScript": "programming",
  "Zephir": "programming",
  "Zig": "programming",
  "Zimpl": "programming",
  "Zmodel": "data",
  "cURL Config": "data",
  "crontab": "data",
  "desktop": "data",
  "dircolors": "data",
  "eC": "programming",
  "edn": "data",
  "fish": "programming",
  "hoon": "programming",
  "iCalendar": "data",
  "jq": "programming",
  "kvlang": "markup",
  "mIRC Script": "programming",
  "mcfunction": "programming",
  "mdsvex": "markup",
  "mupad": "programming",
  "nanorc": "data",
  "nesC": "programming",
  "ooc": "programming",
  "pkg-config": "data",
  "q": "programming",
  "reStructuredText": "prose",
  "sed": "programming",
  "templ": "markup",
  "ucode": "programming",
  "vCard": "data",
  "wisp": "programming",
  "xBase": "programming"
};
